import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * A single reference sidebar. Ordering and category metadata live next to the
 * content itself (`sidebar_position` front matter and `_category_.json`), so
 * adding a page never requires editing this file.
 */
const sidebars: SidebarsConfig = {
  reference: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
